# Generated by Django 3.1.3 on 2020-11-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_images', models.CharField(max_length=30)),
                ('travel_images', models.CharField(max_length=30)),
                ('gaming_images', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=30)),
                ('image_name', models.CharField(max_length=60)),
                ('image_description', models.CharField(max_length=120)),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallary.cartegory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallary.location')),
            ],
        ),
    ]
