# Generated by Django 3.1.3 on 2020-11-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0002_auto_20201113_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartegory',
            old_name='food_images',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cartegory',
            name='gaming_images',
        ),
        migrations.RemoveField(
            model_name='cartegory',
            name='travel_images',
        ),
    ]
