# Generated by Django 3.1.3 on 2020-11-13 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0003_auto_20201113_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
