# Generated by Django 3.1.3 on 2020-11-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0005_auto_20201113_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
    ]
