# Generated by Django 3.1.3 on 2020-11-15 19:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0009_auto_20201115_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default='./static/images/jerin-j-DcdW4R7eMOg-unsplash.jpg', max_length=255, verbose_name='image'),
        ),
    ]
